### ISSUE TITLE
float parameter ranges not working in humble

### ISSUE THREAD

**Issue by christianrauch** [ros-visualization/rqt_reconfigure#116]
I switched from galactic to humble and now get the error:
```
[WARN] [1653783508.027148631] [rqt_reconfigure]: Failed to retrieve parameters from node: setSingleStep(self, int): argument 1 has unexpected type 'float'
```

I can reproduce this with a float parameter:
```cpp
rcl_interfaces::msg::ParameterDescriptor param_descr;
rcl_interfaces::msg::FloatingPointRange range_float;
range_float.from_value = 10;
range_float.to_value = 20;
param_descr.floating_point_range = {range_float};
declare_parameter("test", 15.0, param_descr);
```

**Comment by Flova** [comment]
Same here, I also encountered this issue on rolling under 22.04. It was not present in 20.04. If the node runs of 22.04 and the rqt is still on 20.04 it also works, so it seems to be the rqt plugin that is responsible.

**Comment by christianrauch** [comment]
Fixed by https://github.com/ros-visualization/rqt_reconfigure/pull/117.
