### ISSUE TITLE
Crash when value not in enum list

### ISSUE THREAD

**Issue by lucasw** [ros-visualization/rqt_reconfigure#13]
Example:

The pid package https://bitbucket.org/AndyZe/pid has an enum

```
...
K_scale_enum = gen.enum([ gen.const("scale_tenth", double_t, 0.1, "Scale by 0.1"),
                           gen.const("scale_unity",   double_t, 1.0, "No scaling"),
                           gen.const("scale_ten",  double_t, 10.0, "Scale by 10"),
                           gen.const("scale_hundred", double_t, 100.0, "Scale by 100")],
                           "Scale factor for K setting")

gen.add("Kp_scale", double_t, 0, "Kp scale", 10, 0.1, 100, edit_method = K_scale_enum)
...
```

If I ignore the fact it is an enum and set it to some other value the rqt plugin crashes:

```
roslaunch pid servo_sim.launch
rosrun dynamic_reconfigure dynparam set /left_wheel_pid Kp_scale 2.7
```
Then click on /left_wheel_pid in rqt_reconfigure:

```
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/client.py", line 271, in set_config_callback
    self._config_callback(self.config)
  File "/home/lucasw/tmp_catkin_ws/src/rqt_reconfigure/src/rqt_reconfigure/dynreconf_client_widget.py", line 113, in config_callback
    widget.update_value(config[widget.param_name])
  File "/home/lucasw/tmp_catkin_ws/src/rqt_reconfigure/src/rqt_reconfigure/param_editors.py", line 439, in update_value
    self._update_signal.emit(self.values.index(value))
ValueError: 2.7 is not in list
```

The obvious fix is to check self.values.index before doing this:

```   
self._update_signal.emit(self.values.index(value))
```
It could find the nearest legitimate value and set it to that instead, or just reject it with a warning.
(and I can pr a fix later)

And perhaps dynamic reconfigure itself shouldn't have let me set that value in the first place.

**Comment by cottsay** [comment]
I can't get dynparam to even allow me to set the enum to an invalid value - it keeps rounding to the nearest appropriate value every time I try. Even setting the value to be invalid using `rosparam` before the dynamic reconfigure server is started results in resetting of the value on startup.

Can you confirm this is still a problem, and give me some precise repro steps?
