### ISSUE TITLE
Text form (on the right) does not set the value

### ISSUE THREAD

**Issue by rastaxe** [ros-visualization/rqt_reconfigure#16]
In kinetic (Ubuntu 16.04), the use of the text form on the right side does not set the value. In particular, it works only once, after the use of the bar. 
I am not totally sure, but in the past, this bug did not show up.

**Comment by cottsay** [comment]
This issue has been untouched for a couple of years now. If anyone is able to give me some instruction on how to reproduce the issue, please feel free to comment and/or reopen the issue.

Thanks.
