### ISSUE TITLE
rqt_reconfigure does not display any parameters

### ISSUE THREAD

**Issue by csperbeck6** [ros-visualization/rqt_reconfigure#18]
When I execute "rosrun rqt_reconfigure rqt_reconfigure", the gui window pops up, but I see no parameters to change. Am I missing some installation or configuration to do this? This is what appears when I execute the command:
![rqt_reconfigure](https://user-images.githubusercontent.com/16808258/35629693-49177360-066d-11e8-9945-7e64523087cf.png)

**Comment by 130s** [comment]
How is this different from https://github.com/ros-visualization/rqt_reconfigure/issues/4?

**Comment by cottsay** [comment]
@csperbeck6, are you still having this issue? The [troubleshooting guide](http://wiki.ros.org/rqt_reconfigure#Troubleshoot) talks about using the command line dynamic reconfigure client to confirm what `rqt_reconfigure` is showing. Can you give that a shot?

**Comment by cottsay** [comment]
After getting no response from @csperbeck6 for quite some time, I'm going to close this issue. If you're still having problems and have time to work with me to reproduce them, please feel free to re-open this issue.
