### ISSUE TITLE
Cannot select any node if many nodes are running

### ISSUE THREAD

**Issue by furushchev** [ros-visualization/rqt_reconfigure#19]
Hi, I'm a user of PR2 and have a problem to set params with `rqt_reconfigure`.
When clicking any node in the tree view, the GUI often (really often!) hangs and goes black, and the only thing I can do is to reboot `rqt_reconfigure` node.

I can also see a lot of errors when this node is started like as follows:

```
Exception in thread Thread-114:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/furushchev/ros/kinetic/src/ros-visualization/rqt_reconfigure/src/rqt_reconfigure/treenode_qstditem.py", line 67, in run
    self._param_name_raw))
ROSException: timeout exceeded while waiting for service /kinect_head_external/rgb_rectify_mono/set_parametersTreenodeQstdItem. Couldn't connect to /kinect_head_external/rgb_rectify_mono
```

![rqt_dead](https://user-images.githubusercontent.com/1901008/36639300-1fc8adf0-1a4d-11e8-8015-f47ed39e62f0.png)

**Comment by furushchev** [comment]
@cottsay kindly ping to the maintainer. Any proceedings?

**Comment by cottsay** [comment]
A apologize, @furushchev. A couple of other items are pending for this package now, including a release for Melodic. I'll prioritize this fix and another, followed by a Melodic, Lunar and Kinetic.

**Comment by furushchev** [comment]
@cottsay No problem! Thank you for your hard work! 👍
