### ISSUE TITLE
rqt_reconfigure) to be capable of showing only certain parameters

### ISSUE THREAD

**Issue by dirk-thomas** [ros-visualization/rqt_reconfigure#2]
_From @130s on March 19, 2013 7:29_

In the cases where the users know that the parameters they need to interact with, loading the parameters of all available nodes might just drop the usability. Either or all of the following is useful:
1. [x] Save the nodes selected in the previous run.
2. [x] Allow the developers who make `rqt` plugin that depends on `rqt_reconfigure` to pre-select certain nodes

Particularly, I now start having an impression that the majority of the `reconfigure` users might already know which nodes & parameters they need.

_Copied from original issue: ros-visualization/rqt_common_plugins#49_

**Comment by cottsay** [comment]
> Save the nodes selected in the previous run

Implemented in #79

> ...pre-select certain nodes

Pre-selection from command line was fixed in #77, so I'm calling that complete.
