### ISSUE TITLE
Release into Melodic

### ISSUE THREAD

**Issue by clalancette** [ros-visualization/rqt_reconfigure#22]
It looks like all of the dependencies for this package are available in Melodic, so it would be great to get it released there.  Thanks in advance.

**Comment by 130s** [comment]
@cottsay I can offer to co-maintain if that helps (as I actively use this package), and help the release. If that's fine I just need a write access to this and release repo.

**Comment by clalancette** [comment]
Ping?  Can we get this released into Melodic, please?  Thanks.

**Comment by cottsay** [comment]
I just got the other fixes merged yesterday. The melodic release is complete: https://github.com/ros/rosdistro/pull/17545

@130s, you actually used to be a maintainer for this package. If you'd like to be again, go ahead and open a PR to add yourself to the package.xml, and I'll grant you access to the repos.

**Comment by clalancette** [comment]
Thank you!
