### ISSUE TITLE
Undefined variables in debug statement

### ISSUE THREAD

**Issue by timonegk** [ros-visualization/rqt_reconfigure#29]
In https://github.com/ros-visualization/rqt_reconfigure/blob/master/src/rqt_reconfigure/dynreconf_client_widget.py#L106, the variables `name` and `v` are used, even though they do not exist. This results in a NameError.

**Comment by GabrielQuik** [comment]
Having a similar issue myself.

**Comment by GabrielQuik** [comment]
I solved the issue by deleting /anaconda3 folder

**Comment by timonegk** [comment]
This was apparently closed in #35.
