### ISSUE TITLE
rqt_reconfigure resize disabled with qt5

### ISSUE THREAD

**Issue by dirk-thomas** [ros-visualization/rqt_reconfigure#5]
_From @nxdefiant on April 24, 2017 10:41_

In kinetic the rqt_reconfigure GUI does not allow resize between the left and the right column. This is problematic for e.g. reconfigure params with middle to longer text and reduces the overall usability.

_Copied from original issue: ros-visualization/rqt_common_plugins#450_

**Comment by nxdefiant** [comment]
ros-visualization/rqt_common_plugins#417 has additional details.

**Comment by paulsammut** [comment]
![screenshot_2017-09-13_14-02-16](https://user-images.githubusercontent.com/23394095/30392887-338b8abc-988c-11e7-9e4f-b6e82c796508.png)
This is an extremely annoying problem

**Comment by dirk-thomas** [comment]
Please consider to provide a PR for this. The previously proposed patch (ros-visualization/rqt_common_plugins#417) didn't work.

**Comment by paulsammut** [comment]
Anything on this? I tried inserting this in node_selector_widget.py:

`self._node_selector_view.header().setSectionResizeMode(0, QHeaderView.ResizeToContents)  `

but i get a segfault on launch. Xenial with Kinetic. Is there any quick line I can inject somewhere that will let me see the text in the tree?

**Comment by cottsay** [comment]
Ack, I'll bump this to the top of my queue.

**Comment by nxdefiant** [comment]
paulsammut, did you have any dynreconf enabled nodes running when it was crashing?

**Comment by paulsammut** [comment]
@nxdefiant, I did not! 

Lo and behold, I ran it after loading up some dynamic reconfigure nodes and it works! 

![capture](https://user-images.githubusercontent.com/23394095/30451753-fdd453b4-9961-11e7-8e5d-ecabac392b81.PNG)

**Comment by nxdefiant** [comment]
As I thought, protecting the line with
`if self._node_selector_view.header().length() > 0:`
should do it.

**Comment by paulsammut** [comment]
Just FYI and in an effort to make a better rqt_reconfigure. With that fix, if you run rqt_reconfigure before launching any dynreconf nodes, the tree will not be properly resized. But, I am very very happy with this

**Comment by julianraheema** [comment]
For the binary rqt_reconfigure. go to the /opt/ros/kinetic/share/rqt_reconfigure/resource directory and change node_selector.ui line 95 from false to true.

**Comment by cottsay** [comment]
I believe this was addressed by #11, and should be in the current release. Please reopen if this is still a problem.
